### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cytoo** [cytoo/PmGram#1]
- [ ] Improve the database structure.
- [ ] add management for the added bots by users.
- [ ] clean some of the code, improve the code readability and add some comments.
- [ ] make it more simple and clean.
